Repository InvictoProjects/cultural-events-organizer, pull requests merged in 2024-05, with the labels that each got.

#16 CEO-2: Add CRUD operations for Events
  src/main/kotlin/com/invictoprojects/Application.kt
  src/main/kotlin/com/invictoprojects/controller/EventController.kt
  src/main/kotlin/com/invictoprojects/model/Event.kt
  src/main/kotlin/com/invictoprojects/repository/EventRepository.kt
  src/main/kotlin/com/invictoprojects/repository/InMemoryEventRepository.kt
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: business logic, feature

#19 CEO-6: Provide access to api with JWT
  build.gradle
  src/main/kotlin/com/invictoprojects/Application.kt
  src/main/kotlin/com/invictoprojects/controller/EventController.kt
  src/main/kotlin/com/invictoprojects/model/RefreshToken.kt
  src/main/kotlin/com/invictoprojects/model/Role.kt
  src/main/kotlin/com/invictoprojects/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/invictoprojects/repository/UserRepository.kt
  src/main/kotlin/com/invictoprojects/security/AuthenticationProviderUserPassword.kt
  src/main/kotlin/com/invictoprojects/security/CustomRefreshTokenPersistence.kt
  src/main/kotlin/com/invictoprojects/service/UserService.kt
  src/main/kotlin/com/invictoprojects/service/impl/UserServiceImpl.kt
  src/main/resources/application.yml
  src/test/kotlin/com/invictoprojects/CulturalEventsOrganizerTest.kt
Labels: business logic, feature, security

#21 CEO-8: Ticket functionality
  src/main/kotlin/com/invictoprojects/controller/EventController.kt
  src/main/kotlin/com/invictoprojects/controller/TicketController.kt
  src/main/kotlin/com/invictoprojects/dto/PurchaseRequest.kt
  src/main/kotlin/com/invictoprojects/model/Ticket.kt
  src/main/kotlin/com/invictoprojects/repository/TicketRepository.kt
  src/main/kotlin/com/invictoprojects/service/TicketService.kt
  src/main/kotlin/com/invictoprojects/service/impl/TicketServiceImpl.kt
Labels: business logic, feature

#22 CEO-10: Add User blocking/unblocking feature
  src/main/kotlin/com/invictoprojects/controller/AdminController.kt
  src/main/kotlin/com/invictoprojects/controller/EventController.kt
  src/main/kotlin/com/invictoprojects/controller/TicketController.kt
  src/main/kotlin/com/invictoprojects/dto/BlockDto.kt
  src/main/kotlin/com/invictoprojects/model/User.kt
  src/main/kotlin/com/invictoprojects/security/AuthenticationProviderUserPassword.kt
  src/main/kotlin/com/invictoprojects/service/UserService.kt
  src/main/kotlin/com/invictoprojects/service/impl/UserServiceImpl.kt
Labels: business logic, feature

#35 CEO-11: Add event notification
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/kotlin/com/invictoprojects/controller/EventController.kt
  src/main/kotlin/com/invictoprojects/controller/NotificationController.kt
  src/main/kotlin/com/invictoprojects/controller/SignUpController.kt
  src/main/kotlin/com/invictoprojects/dto/NotificationDto.kt
  src/main/kotlin/com/invictoprojects/model/Notification.kt
  src/main/kotlin/com/invictoprojects/model/NotificationType.kt
  src/main/kotlin/com/invictoprojects/repository/NotificationRepository.kt
  src/main/kotlin/com/invictoprojects/repository/TicketRepository.kt
  src/main/kotlin/com/invictoprojects/service/NotificationService.kt
  src/main/kotlin/com/invictoprojects/service/TicketService.kt
  src/main/kotlin/com/invictoprojects/service/impl/AuthenticationServiceImpl.kt
  src/main/kotlin/com/invictoprojects/service/impl/EventServiceImpl.kt
  src/main/kotlin/com/invictoprojects/service/impl/NotificationServiceImpl.kt
  src/main/kotlin/com/invictoprojects/service/impl/TicketServiceImpl.kt
  src/main/kotlin/com/invictoprojects/utils/MappingUtils.kt
Labels: business logic, feature

#36 Provide root/subprojects structure
  event-management-service/build.gradle
  event-management-service/micronaut-cli.yml
  event-management-service/src/main/kotlin/com/invictoprojects/Application.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/AdminController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/NotificationController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/SignUpController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/TicketController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/BlockDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/EventDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/NotificationDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/PurchaseRequest.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/UserDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Event.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/EventType.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Notification.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/NotificationType.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/RefreshToken.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Role.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Ticket.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/User.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/EventRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/NotificationRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/RefreshTokenRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/TicketRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/UserRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/security/AuthenticationProviderUserPassword.kt
  event-management-service/src/main/kotlin/com/invictoprojects/security/CustomPasswordEncoder.kt
  event-management-service/src/main/kotlin/com/invictoprojects/security/CustomRefreshTokenPersistence.kt
  event-management-service/src/main/kotlin/com/invictoprojects/security/PasswordEncoderConfiguration.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/AuthenticationService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/EventService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/NotificationService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/TicketService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/UserService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/AuthenticationServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/NotificationServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/TicketServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/UserServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/utils/MappingUtils.kt
  event-management-service/src/main/resources/application.yml
  event-management-service/src/main/resources/logback.xml
  event-management-service/src/test/resources/application.yml
  settings.gradle
Labels: refactoring

#37 CEO-12: Add Infrastructure Code
  event-management-service/build.gradle
  event-management-service/src/main/resources/application.yml
  infrastructure/terraform/alb.tf
  infrastructure/terraform/ecs.tf
  infrastructure/terraform/iam.tf
  infrastructure/terraform/output.tf
  infrastructure/terraform/provider.tf
  infrastructure/terraform/rds.tf
  infrastructure/terraform/security_groups.tf
  infrastructure/terraform/task_definition.json.tpl
  infrastructure/terraform/variables.tf
  infrastructure/terraform/vpc.tf
Labels: cloud infrastructure, feature

#38 CEO 13 add notification cleanup service
  infrastructure/terraform/iam.tf
  infrastructure/terraform/notification_cleanup_lambda.tf
  infrastructure/terraform/security_groups.tf
  notification-cleanup-service/build.gradle
  notification-cleanup-service/micronaut-cli.yml
  notification-cleanup-service/src/main/kotlin/com/invictoprojects/ncs/CleanupProperties.kt
  notification-cleanup-service/src/main/kotlin/com/invictoprojects/ncs/FunctionRequestHandler.kt
  notification-cleanup-service/src/main/kotlin/com/invictoprojects/ncs/Notification.kt
  notification-cleanup-service/src/main/kotlin/com/invictoprojects/ncs/NotificationRepository.kt
  notification-cleanup-service/src/main/resources/application.yml
  notification-cleanup-service/src/main/resources/logback.xml
  notification-cleanup-service/src/test/kotlin/com/invictoprojects/ncs/HomeControllerTest.kt
  notification-cleanup-service/src/test/kotlin/com/invictoprojects/ncs/NotificationCleanupServiceTest.kt
  notification-cleanup-service/src/test/resources/application-test.yml
  settings.gradle
Labels: business logic, feature

#39 CEO-14: Add Event Feedback/Rating
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventFeedbackController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/EventFeedbackDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/EventFeedback.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/EventFeedbackRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/TicketRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/EventFeedbackService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/TicketService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventFeedbackServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/TicketServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/UserServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/utils/MappingUtils.kt
Labels: business logic, feature

#40 CEO-14: Add event feedback/rating
  event-management-service/src/main/kotlin/com/invictoprojects/model/NotificationType.kt
  event-monitoring-service/build.gradle
  event-monitoring-service/micronaut-cli.yml
  event-monitoring-service/src/main/kotlin/com/koroliuk/ems/Event.kt
  event-monitoring-service/src/main/kotlin/com/koroliuk/ems/EventRepository.kt
  event-monitoring-service/src/main/kotlin/com/koroliuk/ems/FunctionRequestHandler.kt
  event-monitoring-service/src/main/kotlin/com/koroliuk/ems/Notification.kt
  event-monitoring-service/src/main/kotlin/com/koroliuk/ems/NotificationRepository.kt
  event-monitoring-service/src/main/resources/application.yml
  event-monitoring-service/src/main/resources/logback.xml
  event-monitoring-service/src/test/kotlin/com/koroliuk/ems/EventMonitoringServiceTest.kt
  event-monitoring-service/src/test/resources/application-test.yml
  infrastructure/terraform/event_monitor.tf
  settings.gradle
Labels: business logic, feature

#42 CEO-16: Add event analytics
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventAnalyticsController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventFeedbackController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/TicketController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Event.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/EventAnalytics.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/EventAnalyticsEnvelope.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Ticket.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/TicketStatus.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/EventFeedbackRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/TicketRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/EventFeedbackService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/EventService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/TicketService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventFeedbackServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/TicketServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/utils/MappingUtils.kt
Labels: business logic, feature

#43 NO-TASK: Update README.md
  README.md
Labels: documentation

#44 CEO-17: Provide Waiting List functionality
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/UserController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/EventDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/PurchaseRequest.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Event.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/NotificationType.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/WaitList.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/WaitListRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/EventService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/TicketService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/WaitListService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/TicketServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/WaitListServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/utils/MappingUtils.kt
Labels: business logic, feature

#45 CEO-18: Add Media functionality for Events
  event-management-service/build.gradle
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/EventMedia.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/EventMediaRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/EventMediaService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventMediaServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/S3Service.kt
  event-management-service/src/main/resources/application.yml
  infrastructure/terraform/iam.tf
  infrastructure/terraform/s3.tf
Labels: business logic, feature

#46 CEO-19 Adding a reminder to the user about an upcoming event and prov…
  event-management-service/src/main/kotlin/com/invictoprojects/controller/DiscountCodeController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/DiscountCodeRequest.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/EventDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/PurchaseRequest.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/DiscountCode.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Event.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Ticket.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/DiscountCodeRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/DiscountService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/TicketService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/DiscountCodeServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/TicketServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/utils/MappingUtils.kt
  event-monitoring-service/build.gradle
  event-monitoring-service/src/main/kotlin/com/invictoprojects/ems/Event.kt
  event-monitoring-service/src/main/kotlin/com/invictoprojects/ems/EventRepository.kt
  event-monitoring-service/src/main/kotlin/com/invictoprojects/ems/FunctionRequestHandler.kt
  event-monitoring-service/src/main/kotlin/com/invictoprojects/ems/Notification.kt
  event-monitoring-service/src/main/kotlin/com/invictoprojects/ems/NotificationRepository.kt
  event-monitoring-service/src/main/kotlin/com/koroliuk/ems/FunctionRequestHandler.kt
  event-monitoring-service/src/test/kotlin/com/invictoprojects/ems/EventMonitoringServiceTest.kt
Labels: business logic, feature

#47 CEO-21: Add receiving events for a specific user
  event-management-service/src/main/kotlin/com/invictoprojects/controller/ComplaintController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/UserController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/ComplaintDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Complaint.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/ComplaintStatus.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Event.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/NotificationType.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/ComplaintRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/EventRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/CompliantService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/EventService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/TicketService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/ComplaintServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/TicketServiceImpl.kt
Labels: business logic, feature

#48 CEO-23: Introduce functionality of private events
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/EventDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Event.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/EventRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/EventService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/EventServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/utils/MappingUtils.kt
Labels: business logic, feature

#49 CEO-24: Implement multiple managers possibility for event
  event-management-service/src/main/kotlin/com/invictoprojects/controller/ComplaintController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventAnalyticsController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventFeedbackController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Event.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/DiscountCodeRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/EventRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/DiscountCodeService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/ComplaintServiceImpl.kt
  event-management-service/src/main/kotlin/com/invictoprojects/utils/MappingUtils.kt
Labels: business logic, feature

#50 NOISSUE: Add more badges to README.md
  README.md
Labels: chore, documentation

#51 CEO-25: Provide volunteers for events
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EventController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/dto/EventDto.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/Event.kt
  event-management-service/src/main/kotlin/com/invictoprojects/model/VolunteerApplication.kt
  event-management-service/src/main/kotlin/com/invictoprojects/repository/VolunteerApplicationRepository.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/VolunteerApplicationService.kt
  event-management-service/src/main/kotlin/com/invictoprojects/service/impl/VolunteerApplicationServiceImpl.kt
Labels: business logic, feature

#52 CEO-26: Adding Email sending functionality
  email-sender-service/build.gradle
  email-sender-service/micronaut-cli.yml
  email-sender-service/src/main/kotlin/com/ess/EmailService.kt
  email-sender-service/src/main/kotlin/com/ess/FunctionRequestHandler.kt
  email-sender-service/src/main/resources/application.yml
  email-sender-service/src/main/resources/logback.xml
  event-management-service/build.gradle
  event-management-service/src/main/kotlin/com/invictoprojects/controller/EmailController.kt
  event-management-service/src/main/kotlin/com/invictoprojects/controller/HealthController.kt
  event-management-service/src/main/resources/application.yml
  infrastructure/terraform/ecs.tf
  infrastructure/terraform/iam.tf
  infrastructure/terraform/route53.tf
  infrastructure/terraform/sqs.tf
  infrastructure/terraform/task_definition.json.tpl
  infrastructure/terraform/variables.tf
  notification-cleanup-service/src/test/kotlin/com/invictoprojects/ncs/HomeControllerTest.kt
  notification-cleanup-service/src/test/kotlin/com/invictoprojects/ncs/NotificationCleanupServiceTest.kt
  settings.gradle
Labels: business logic, feature
